// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: unifront_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UnifrontClient is the client API for Unifront service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UnifrontClient interface {
	TokenPrice(ctx context.Context, in *TokenPriceRequest, opts ...grpc.CallOption) (*TokenPriceResponse, error)
	TokenPriceV2(ctx context.Context, in *TokenPriceRequest, opts ...grpc.CallOption) (*TokenPriceResponseV2, error)
	Balance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	ProcessingFee(ctx context.Context, in *ProcessingFeeRequest, opts ...grpc.CallOption) (*ProcessingFeeResponse, error)
	Nonce(ctx context.Context, in *NonceRequest, opts ...grpc.CallOption) (*NonceResponse, error)
	SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error)
	ListTransaction(ctx context.Context, in *ListTransactionRequest, opts ...grpc.CallOption) (*ListTransactionResponse, error)
	UserData(ctx context.Context, in *UserDataRequest, opts ...grpc.CallOption) (*UserDataResponse, error)
	// ExchangeTokens(ctx context.Context, in *ExchangeTokenRequest, opts ...grpc.CallOption) (*ExchangeTokenResponse, error)
	// ExchangeQuote(ctx context.Context, in *ExchangeQuoteRequest, opts ...grpc.CallOption) (*ExchangeQuoteResponse, error)
	// ExchangeMultiQuote(ctx context.Context, in *ExchangeMultiQuoteRequest, opts ...grpc.CallOption) (*ExchangeMultiQuoteResponse, error)
	// ExchangeSwap(ctx context.Context, in *ExchangeSwapRequest, opts ...grpc.CallOption) (*ExchangeSwapResponse, error)
	// ExchangeMultiSwap(ctx context.Context, in *ExchangeMultiSwapRequest, opts ...grpc.CallOption) (*ExchangeMultipleSwapResponse, error)
	// ExchangeSwapExecute(ctx context.Context, in *ExchangeSwapExecuteRequest, opts ...grpc.CallOption) (*ExchangeSwapExecuteResponse, error)
	// FreeTradeCount(ctx context.Context, in *FreeTradeCountRequest, opts ...grpc.CallOption) (*FreeTradeCountResponse, error)
	// ExchangeTokenApprove(ctx context.Context, in *TokenApprovalRequest, opts ...grpc.CallOption) (*TokenApprovalResponse, error)
	// ExchangeSwapSignature(ctx context.Context, in *ExchangeSignatureRequest, opts ...grpc.CallOption) (*ExchangeSignatureResponse, error)
	TxStatus(ctx context.Context, in *TxStatusRequest, opts ...grpc.CallOption) (*TxStatusResponse, error)
	GasLimit(ctx context.Context, in *GasLimitRequest, opts ...grpc.CallOption) (*GasLimitResponse, error)
	TokenInfo(ctx context.Context, in *TokenInfoRequest, opts ...grpc.CallOption) (*TokenInfoResponse, error)
	TokenDetail(ctx context.Context, in *TokenDetailRequest, opts ...grpc.CallOption) (*TokenDetailResponse, error)
	BridgeChain(ctx context.Context, in *BridgeChainRequest, opts ...grpc.CallOption) (*BridgeChainResponse, error)
	BridgeChainTokens(ctx context.Context, in *BridgeChainTokensRequest, opts ...grpc.CallOption) (*BridgeChainTokensResponse, error)
	BridgeQuote(ctx context.Context, in *BridgeQuoteRequest, opts ...grpc.CallOption) (*BridgeQuoteResponse, error)
	BridgeTransaction(ctx context.Context, in *BridgeTransactionRequest, opts ...grpc.CallOption) (*BridgeTransactionResponse, error)
	BridgeTransactionStatus(ctx context.Context, in *BridgeTransactionStatusRequest, opts ...grpc.CallOption) (*BridgeTransactionStatusResponse, error)
	Allowance(ctx context.Context, in *AllowanceRequest, opts ...grpc.CallOption) (*AllowanceResponse, error)
	Approve(ctx context.Context, in *ApprovalRequest, opts ...grpc.CallOption) (*ApprovalResponse, error)
	GetNftCollections(ctx context.Context, in *NftCollectionRequest, opts ...grpc.CallOption) (*ListNftCollectionResponse, error)
	GetValidators(ctx context.Context, in *CosmosValidatorsRequest, opts ...grpc.CallOption) (*CosmosValidatorsResponse, error)
	GetCosmosAprRates(ctx context.Context, in *CosmosAprRatesRequest, opts ...grpc.CallOption) (*CosmosAprRatesResponse, error)
	GetDelegations(ctx context.Context, in *CosmosDelegationsRequest, opts ...grpc.CallOption) (*CosmosDelegationsResponse, error)
	GetCosmosCDPParams(ctx context.Context, in *CosmosCDPParametersRequest, opts ...grpc.CallOption) (*CosmosCDPParametersResponse, error)
	// rpc getAccountInfo(getAccountInfoRequest) returns (getAccountInfoResponse);
	// rpc getFees(GetFeeRequest) returns (GetFeeResponse);
	// rpc getTokenAccountBalance(GetTokenAccBalanceRequest) returns (GetTokenAccBalanceResponse);
	// rpc getTransaction(GetTransactionRequest) returns(GetTransactionResponse);
	CosmosAssets(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*CosmosAssetResponse, error)
	CosmosSendTx(ctx context.Context, in *CosmosSendTxRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error)
	CosmosSimulateTX(ctx context.Context, in *CosmosSimulateTxRequest, opts ...grpc.CallOption) (*CosmosSimulateTxResponse, error)
	CosmosGetBlockHeight(ctx context.Context, in *GetCosmosBlockHeightRequest, opts ...grpc.CallOption) (*GetCosmosBlockHeightResponse, error)
	GetPositions(ctx context.Context, in *PositionChainData, opts ...grpc.CallOption) (*GetPositionsResponse, error)
	// rpc getAccountInfo(getAccountInfoRequest) returns
	// (getAccountInfoResponse); rpc getFees(GetFeeRequest) returns
	// (GetFeeResponse); rpc getTokenAccountBalance(GetTokenAccBalanceRequest)
	// returns (GetTokenAccBalanceResponse); rpc
	// getTransaction(GetTransactionRequest) returns(GetTransactionResponse);
	BulkApproval(ctx context.Context, in *ApprovalRequest, opts ...grpc.CallOption) (*BulkApprovalResponse, error)
	BulkAllowance(ctx context.Context, in *AllowanceRequest, opts ...grpc.CallOption) (*BulkAllowanceResponse, error)
	GetOpportunites(ctx context.Context, in *GetOpportunitiesRequest, opts ...grpc.CallOption) (*GetOpportunitesResponse, error)
}

type unifrontClient struct {
	cc grpc.ClientConnInterface
}

func NewUnifrontClient(cc grpc.ClientConnInterface) UnifrontClient {
	return &unifrontClient{cc}
}

func (c *unifrontClient) TokenPrice(ctx context.Context, in *TokenPriceRequest, opts ...grpc.CallOption) (*TokenPriceResponse, error) {
	out := new(TokenPriceResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/tokenPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) TokenPriceV2(ctx context.Context, in *TokenPriceRequest, opts ...grpc.CallOption) (*TokenPriceResponseV2, error) {
	out := new(TokenPriceResponseV2)
	err := c.cc.Invoke(ctx, "/proto.Unifront/tokenPriceV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) Balance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/balance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) ProcessingFee(ctx context.Context, in *ProcessingFeeRequest, opts ...grpc.CallOption) (*ProcessingFeeResponse, error) {
	out := new(ProcessingFeeResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/processingFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) Nonce(ctx context.Context, in *NonceRequest, opts ...grpc.CallOption) (*NonceResponse, error) {
	out := new(NonceResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/nonce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error) {
	out := new(SendTransactionResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/sendTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) ListTransaction(ctx context.Context, in *ListTransactionRequest, opts ...grpc.CallOption) (*ListTransactionResponse, error) {
	out := new(ListTransactionResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/listTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) UserData(ctx context.Context, in *UserDataRequest, opts ...grpc.CallOption) (*UserDataResponse, error) {
	out := new(UserDataResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/userData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// func (c *unifrontClient) ExchangeTokens(ctx context.Context, in *ExchangeTokenRequest, opts ...grpc.CallOption) (*ExchangeTokenResponse, error) {
// 	out := new(ExchangeTokenResponse)
// 	err := c.cc.Invoke(ctx, "/proto.Unifront/exchangeTokens", in, out, opts...)
// 	if err != nil {
// 		return nil, err
// 	}
// 	return out, nil
// }

// func (c *unifrontClient) ExchangeQuote(ctx context.Context, in *ExchangeQuoteRequest, opts ...grpc.CallOption) (*ExchangeQuoteResponse, error) {
// 	out := new(ExchangeQuoteResponse)
// 	err := c.cc.Invoke(ctx, "/proto.Unifront/exchangeQuote", in, out, opts...)
// 	if err != nil {
// 		return nil, err
// 	}
// 	return out, nil
// }

// func (c *unifrontClient) ExchangeMultiQuote(ctx context.Context, in *ExchangeMultiQuoteRequest, opts ...grpc.CallOption) (*ExchangeMultiQuoteResponse, error) {
// 	out := new(ExchangeMultiQuoteResponse)
// 	err := c.cc.Invoke(ctx, "/proto.Unifront/exchangeMultiQuote", in, out, opts...)
// 	if err != nil {
// 		return nil, err
// 	}
// 	return out, nil
// }

// func (c *unifrontClient) ExchangeSwap(ctx context.Context, in *ExchangeSwapRequest, opts ...grpc.CallOption) (*ExchangeSwapResponse, error) {
// 	out := new(ExchangeSwapResponse)
// 	err := c.cc.Invoke(ctx, "/proto.Unifront/exchangeSwap", in, out, opts...)
// 	if err != nil {
// 		return nil, err
// 	}
// 	return out, nil
// }

// func (c *unifrontClient) ExchangeMultiSwap(ctx context.Context, in *ExchangeMultiSwapRequest, opts ...grpc.CallOption) (*ExchangeMultipleSwapResponse, error) {
// 	out := new(ExchangeMultipleSwapResponse)
// 	err := c.cc.Invoke(ctx, "/proto.Unifront/exchangeMultiSwap", in, out, opts...)
// 	if err != nil {
// 		return nil, err
// 	}
// 	return out, nil
// }

// func (c *unifrontClient) ExchangeSwapExecute(ctx context.Context, in *ExchangeSwapExecuteRequest, opts ...grpc.CallOption) (*ExchangeSwapExecuteResponse, error) {
// 	out := new(ExchangeSwapExecuteResponse)
// 	err := c.cc.Invoke(ctx, "/proto.Unifront/exchangeSwapExecute", in, out, opts...)
// 	if err != nil {
// 		return nil, err
// 	}
// 	return out, nil
// }

// func (c *unifrontClient) FreeTradeCount(ctx context.Context, in *FreeTradeCountRequest, opts ...grpc.CallOption) (*FreeTradeCountResponse, error) {
// 	out := new(FreeTradeCountResponse)
// 	err := c.cc.Invoke(ctx, "/proto.Unifront/FreeTradeCount", in, out, opts...)
// 	if err != nil {
// 		return nil, err
// 	}
// 	return out, nil
// }

// func (c *unifrontClient) ExchangeTokenApprove(ctx context.Context, in *TokenApprovalRequest, opts ...grpc.CallOption) (*TokenApprovalResponse, error) {
// 	out := new(TokenApprovalResponse)
// 	err := c.cc.Invoke(ctx, "/proto.Unifront/ExchangeTokenApprove", in, out, opts...)
// 	if err != nil {
// 		return nil, err
// 	}
// 	return out, nil
// }

// func (c *unifrontClient) ExchangeSwapSignature(ctx context.Context, in *ExchangeSignatureRequest, opts ...grpc.CallOption) (*ExchangeSignatureResponse, error) {
// 	out := new(ExchangeSignatureResponse)
// 	err := c.cc.Invoke(ctx, "/proto.Unifront/exchangeSwapSignature", in, out, opts...)
// 	if err != nil {
// 		return nil, err
// 	}
// 	return out, nil
// }

func (c *unifrontClient) TxStatus(ctx context.Context, in *TxStatusRequest, opts ...grpc.CallOption) (*TxStatusResponse, error) {
	out := new(TxStatusResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/txStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) GasLimit(ctx context.Context, in *GasLimitRequest, opts ...grpc.CallOption) (*GasLimitResponse, error) {
	out := new(GasLimitResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/gasLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) TokenInfo(ctx context.Context, in *TokenInfoRequest, opts ...grpc.CallOption) (*TokenInfoResponse, error) {
	out := new(TokenInfoResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/tokenInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) TokenDetail(ctx context.Context, in *TokenDetailRequest, opts ...grpc.CallOption) (*TokenDetailResponse, error) {
	out := new(TokenDetailResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/tokenDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) BridgeChain(ctx context.Context, in *BridgeChainRequest, opts ...grpc.CallOption) (*BridgeChainResponse, error) {
	out := new(BridgeChainResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/bridgeChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) BridgeChainTokens(ctx context.Context, in *BridgeChainTokensRequest, opts ...grpc.CallOption) (*BridgeChainTokensResponse, error) {
	out := new(BridgeChainTokensResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/bridgeChainTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) BridgeQuote(ctx context.Context, in *BridgeQuoteRequest, opts ...grpc.CallOption) (*BridgeQuoteResponse, error) {
	out := new(BridgeQuoteResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/bridgeQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) BridgeTransaction(ctx context.Context, in *BridgeTransactionRequest, opts ...grpc.CallOption) (*BridgeTransactionResponse, error) {
	out := new(BridgeTransactionResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/bridgeTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) BridgeTransactionStatus(ctx context.Context, in *BridgeTransactionStatusRequest, opts ...grpc.CallOption) (*BridgeTransactionStatusResponse, error) {
	out := new(BridgeTransactionStatusResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/bridgeTransactionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) Allowance(ctx context.Context, in *AllowanceRequest, opts ...grpc.CallOption) (*AllowanceResponse, error) {
	out := new(AllowanceResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/allowance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) Approve(ctx context.Context, in *ApprovalRequest, opts ...grpc.CallOption) (*ApprovalResponse, error) {
	out := new(ApprovalResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/approve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) GetNftCollections(ctx context.Context, in *NftCollectionRequest, opts ...grpc.CallOption) (*ListNftCollectionResponse, error) {
	out := new(ListNftCollectionResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/GetNftCollections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) GetValidators(ctx context.Context, in *CosmosValidatorsRequest, opts ...grpc.CallOption) (*CosmosValidatorsResponse, error) {
	out := new(CosmosValidatorsResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/GetValidators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) GetCosmosAprRates(ctx context.Context, in *CosmosAprRatesRequest, opts ...grpc.CallOption) (*CosmosAprRatesResponse, error) {
	out := new(CosmosAprRatesResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/GetCosmosAprRates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) GetDelegations(ctx context.Context, in *CosmosDelegationsRequest, opts ...grpc.CallOption) (*CosmosDelegationsResponse, error) {
	out := new(CosmosDelegationsResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/GetDelegations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) GetCosmosCDPParams(ctx context.Context, in *CosmosCDPParametersRequest, opts ...grpc.CallOption) (*CosmosCDPParametersResponse, error) {
	out := new(CosmosCDPParametersResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/GetCosmosCDPParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) CosmosAssets(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*CosmosAssetResponse, error) {
	out := new(CosmosAssetResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/cosmosAssets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) CosmosSendTx(ctx context.Context, in *CosmosSendTxRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error) {
	out := new(SendTransactionResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/cosmosSendTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) CosmosSimulateTX(ctx context.Context, in *CosmosSimulateTxRequest, opts ...grpc.CallOption) (*CosmosSimulateTxResponse, error) {
	out := new(CosmosSimulateTxResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/cosmosSimulateTX", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) CosmosGetBlockHeight(ctx context.Context, in *GetCosmosBlockHeightRequest, opts ...grpc.CallOption) (*GetCosmosBlockHeightResponse, error) {
	out := new(GetCosmosBlockHeightResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/cosmosGetBlockHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) GetPositions(ctx context.Context, in *PositionChainData, opts ...grpc.CallOption) (*GetPositionsResponse, error) {
	out := new(GetPositionsResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/getPositions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) BulkApproval(ctx context.Context, in *ApprovalRequest, opts ...grpc.CallOption) (*BulkApprovalResponse, error) {
	out := new(BulkApprovalResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/BulkApproval", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) BulkAllowance(ctx context.Context, in *AllowanceRequest, opts ...grpc.CallOption) (*BulkAllowanceResponse, error) {
	out := new(BulkAllowanceResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/BulkAllowance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unifrontClient) GetOpportunites(ctx context.Context, in *GetOpportunitiesRequest, opts ...grpc.CallOption) (*GetOpportunitesResponse, error) {
	out := new(GetOpportunitesResponse)
	err := c.cc.Invoke(ctx, "/proto.Unifront/GetOpportunites", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnifrontServer is the server API for Unifront service.
// All implementations must embed UnimplementedUnifrontServer
// for forward compatibility
type UnifrontServer interface {
	TokenPrice(context.Context, *TokenPriceRequest) (*TokenPriceResponse, error)
	TokenPriceV2(context.Context, *TokenPriceRequest) (*TokenPriceResponseV2, error)
	Balance(context.Context, *BalanceRequest) (*BalanceResponse, error)
	ProcessingFee(context.Context, *ProcessingFeeRequest) (*ProcessingFeeResponse, error)
	Nonce(context.Context, *NonceRequest) (*NonceResponse, error)
	SendTransaction(context.Context, *SendTransactionRequest) (*SendTransactionResponse, error)
	ListTransaction(context.Context, *ListTransactionRequest) (*ListTransactionResponse, error)
	UserData(context.Context, *UserDataRequest) (*UserDataResponse, error)
	// ExchangeTokens(context.Context, *ExchangeTokenRequest) (*ExchangeTokenResponse, error)
	// ExchangeQuote(context.Context, *ExchangeQuoteRequest) (*ExchangeQuoteResponse, error)
	// ExchangeMultiQuote(context.Context, *ExchangeMultiQuoteRequest) (*ExchangeMultiQuoteResponse, error)
	// ExchangeSwap(context.Context, *ExchangeSwapRequest) (*ExchangeSwapResponse, error)
	// ExchangeMultiSwap(context.Context, *ExchangeMultiSwapRequest) (*ExchangeMultipleSwapResponse, error)
	// ExchangeSwapExecute(context.Context, *ExchangeSwapExecuteRequest) (*ExchangeSwapExecuteResponse, error)
	// FreeTradeCount(context.Context, *FreeTradeCountRequest) (*FreeTradeCountResponse, error)
	// ExchangeTokenApprove(context.Context, *TokenApprovalRequest) (*TokenApprovalResponse, error)
	// ExchangeSwapSignature(context.Context, *ExchangeSignatureRequest) (*ExchangeSignatureResponse, error)
	TxStatus(context.Context, *TxStatusRequest) (*TxStatusResponse, error)
	GasLimit(context.Context, *GasLimitRequest) (*GasLimitResponse, error)
	TokenInfo(context.Context, *TokenInfoRequest) (*TokenInfoResponse, error)
	TokenDetail(context.Context, *TokenDetailRequest) (*TokenDetailResponse, error)
	BridgeChain(context.Context, *BridgeChainRequest) (*BridgeChainResponse, error)
	BridgeChainTokens(context.Context, *BridgeChainTokensRequest) (*BridgeChainTokensResponse, error)
	BridgeQuote(context.Context, *BridgeQuoteRequest) (*BridgeQuoteResponse, error)
	BridgeTransaction(context.Context, *BridgeTransactionRequest) (*BridgeTransactionResponse, error)
	BridgeTransactionStatus(context.Context, *BridgeTransactionStatusRequest) (*BridgeTransactionStatusResponse, error)
	Allowance(context.Context, *AllowanceRequest) (*AllowanceResponse, error)
	Approve(context.Context, *ApprovalRequest) (*ApprovalResponse, error)
	GetNftCollections(context.Context, *NftCollectionRequest) (*ListNftCollectionResponse, error)
	GetValidators(context.Context, *CosmosValidatorsRequest) (*CosmosValidatorsResponse, error)
	GetCosmosAprRates(context.Context, *CosmosAprRatesRequest) (*CosmosAprRatesResponse, error)
	GetDelegations(context.Context, *CosmosDelegationsRequest) (*CosmosDelegationsResponse, error)
	GetCosmosCDPParams(context.Context, *CosmosCDPParametersRequest) (*CosmosCDPParametersResponse, error)
	// rpc getAccountInfo(getAccountInfoRequest) returns (getAccountInfoResponse);
	// rpc getFees(GetFeeRequest) returns (GetFeeResponse);
	// rpc getTokenAccountBalance(GetTokenAccBalanceRequest) returns (GetTokenAccBalanceResponse);
	// rpc getTransaction(GetTransactionRequest) returns(GetTransactionResponse);
	CosmosAssets(context.Context, *BalanceRequest) (*CosmosAssetResponse, error)
	CosmosSendTx(context.Context, *CosmosSendTxRequest) (*SendTransactionResponse, error)
	CosmosSimulateTX(context.Context, *CosmosSimulateTxRequest) (*CosmosSimulateTxResponse, error)
	CosmosGetBlockHeight(context.Context, *GetCosmosBlockHeightRequest) (*GetCosmosBlockHeightResponse, error)
	GetPositions(context.Context, *PositionChainData) (*GetPositionsResponse, error)
	// rpc getAccountInfo(getAccountInfoRequest) returns
	// (getAccountInfoResponse); rpc getFees(GetFeeRequest) returns
	// (GetFeeResponse); rpc getTokenAccountBalance(GetTokenAccBalanceRequest)
	// returns (GetTokenAccBalanceResponse); rpc
	// getTransaction(GetTransactionRequest) returns(GetTransactionResponse);
	BulkApproval(context.Context, *ApprovalRequest) (*BulkApprovalResponse, error)
	BulkAllowance(context.Context, *AllowanceRequest) (*BulkAllowanceResponse, error)
	GetOpportunites(context.Context, *GetOpportunitiesRequest) (*GetOpportunitesResponse, error)
	mustEmbedUnimplementedUnifrontServer()
}

// UnimplementedUnifrontServer must be embedded to have forward compatible implementations.
type UnimplementedUnifrontServer struct {
}

func (UnimplementedUnifrontServer) TokenPrice(context.Context, *TokenPriceRequest) (*TokenPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenPrice not implemented")
}
func (UnimplementedUnifrontServer) TokenPriceV2(context.Context, *TokenPriceRequest) (*TokenPriceResponseV2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenPriceV2 not implemented")
}
func (UnimplementedUnifrontServer) Balance(context.Context, *BalanceRequest) (*BalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Balance not implemented")
}
func (UnimplementedUnifrontServer) ProcessingFee(context.Context, *ProcessingFeeRequest) (*ProcessingFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessingFee not implemented")
}
func (UnimplementedUnifrontServer) Nonce(context.Context, *NonceRequest) (*NonceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Nonce not implemented")
}
func (UnimplementedUnifrontServer) SendTransaction(context.Context, *SendTransactionRequest) (*SendTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTransaction not implemented")
}
func (UnimplementedUnifrontServer) ListTransaction(context.Context, *ListTransactionRequest) (*ListTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransaction not implemented")
}
func (UnimplementedUnifrontServer) UserData(context.Context, *UserDataRequest) (*UserDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserData not implemented")
}
// func (UnimplementedUnifrontServer) ExchangeTokens(context.Context, *ExchangeTokenRequest) (*ExchangeTokenResponse, error) {
// 	return nil, status.Errorf(codes.Unimplemented, "method ExchangeTokens not implemented")
// }
// func (UnimplementedUnifrontServer) ExchangeQuote(context.Context, *ExchangeQuoteRequest) (*ExchangeQuoteResponse, error) {
// 	return nil, status.Errorf(codes.Unimplemented, "method ExchangeQuote not implemented")
// }
// func (UnimplementedUnifrontServer) ExchangeMultiQuote(context.Context, *ExchangeMultiQuoteRequest) (*ExchangeMultiQuoteResponse, error) {
// 	return nil, status.Errorf(codes.Unimplemented, "method ExchangeMultiQuote not implemented")
// }
// func (UnimplementedUnifrontServer) ExchangeSwap(context.Context, *ExchangeSwapRequest) (*ExchangeSwapResponse, error) {
// 	return nil, status.Errorf(codes.Unimplemented, "method ExchangeSwap not implemented")
// }
// func (UnimplementedUnifrontServer) ExchangeMultiSwap(context.Context, *ExchangeMultiSwapRequest) (*ExchangeMultipleSwapResponse, error) {
// 	return nil, status.Errorf(codes.Unimplemented, "method ExchangeMultiSwap not implemented")
// }
// func (UnimplementedUnifrontServer) ExchangeSwapExecute(context.Context, *ExchangeSwapExecuteRequest) (*ExchangeSwapExecuteResponse, error) {
// 	return nil, status.Errorf(codes.Unimplemented, "method ExchangeSwapExecute not implemented")
// }
// func (UnimplementedUnifrontServer) FreeTradeCount(context.Context, *FreeTradeCountRequest) (*FreeTradeCountResponse, error) {
// 	return nil, status.Errorf(codes.Unimplemented, "method FreeTradeCount not implemented")
// }
// func (UnimplementedUnifrontServer) ExchangeTokenApprove(context.Context, *TokenApprovalRequest) (*TokenApprovalResponse, error) {
// 	return nil, status.Errorf(codes.Unimplemented, "method ExchangeTokenApprove not implemented")
// }
// func (UnimplementedUnifrontServer) ExchangeSwapSignature(context.Context, *ExchangeSignatureRequest) (*ExchangeSignatureResponse, error) {
// 	return nil, status.Errorf(codes.Unimplemented, "method ExchangeSwapSignature not implemented")
// }
func (UnimplementedUnifrontServer) TxStatus(context.Context, *TxStatusRequest) (*TxStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TxStatus not implemented")
}
func (UnimplementedUnifrontServer) GasLimit(context.Context, *GasLimitRequest) (*GasLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GasLimit not implemented")
}
func (UnimplementedUnifrontServer) TokenInfo(context.Context, *TokenInfoRequest) (*TokenInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenInfo not implemented")
}
func (UnimplementedUnifrontServer) TokenDetail(context.Context, *TokenDetailRequest) (*TokenDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenDetail not implemented")
}
func (UnimplementedUnifrontServer) BridgeChain(context.Context, *BridgeChainRequest) (*BridgeChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BridgeChain not implemented")
}
func (UnimplementedUnifrontServer) BridgeChainTokens(context.Context, *BridgeChainTokensRequest) (*BridgeChainTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BridgeChainTokens not implemented")
}
func (UnimplementedUnifrontServer) BridgeQuote(context.Context, *BridgeQuoteRequest) (*BridgeQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BridgeQuote not implemented")
}
func (UnimplementedUnifrontServer) BridgeTransaction(context.Context, *BridgeTransactionRequest) (*BridgeTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BridgeTransaction not implemented")
}
func (UnimplementedUnifrontServer) BridgeTransactionStatus(context.Context, *BridgeTransactionStatusRequest) (*BridgeTransactionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BridgeTransactionStatus not implemented")
}
func (UnimplementedUnifrontServer) Allowance(context.Context, *AllowanceRequest) (*AllowanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Allowance not implemented")
}
func (UnimplementedUnifrontServer) Approve(context.Context, *ApprovalRequest) (*ApprovalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Approve not implemented")
}
func (UnimplementedUnifrontServer) GetNftCollections(context.Context, *NftCollectionRequest) (*ListNftCollectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNftCollections not implemented")
}
func (UnimplementedUnifrontServer) GetValidators(context.Context, *CosmosValidatorsRequest) (*CosmosValidatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidators not implemented")
}
func (UnimplementedUnifrontServer) GetCosmosAprRates(context.Context, *CosmosAprRatesRequest) (*CosmosAprRatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCosmosAprRates not implemented")
}
func (UnimplementedUnifrontServer) GetDelegations(context.Context, *CosmosDelegationsRequest) (*CosmosDelegationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDelegations not implemented")
}
func (UnimplementedUnifrontServer) GetCosmosCDPParams(context.Context, *CosmosCDPParametersRequest) (*CosmosCDPParametersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCosmosCDPParams not implemented")
}
func (UnimplementedUnifrontServer) CosmosAssets(context.Context, *BalanceRequest) (*CosmosAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CosmosAssets not implemented")
}
func (UnimplementedUnifrontServer) CosmosSendTx(context.Context, *CosmosSendTxRequest) (*SendTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CosmosSendTx not implemented")
}
func (UnimplementedUnifrontServer) CosmosSimulateTX(context.Context, *CosmosSimulateTxRequest) (*CosmosSimulateTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CosmosSimulateTX not implemented")
}
func (UnimplementedUnifrontServer) CosmosGetBlockHeight(context.Context, *GetCosmosBlockHeightRequest) (*GetCosmosBlockHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CosmosGetBlockHeight not implemented")
}
func (UnimplementedUnifrontServer) GetPositions(context.Context, *PositionChainData) (*GetPositionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPositions not implemented")
}
func (UnimplementedUnifrontServer) BulkApproval(context.Context, *ApprovalRequest) (*BulkApprovalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkApproval not implemented")
}
func (UnimplementedUnifrontServer) BulkAllowance(context.Context, *AllowanceRequest) (*BulkAllowanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkAllowance not implemented")
}
func (UnimplementedUnifrontServer) GetOpportunites(context.Context, *GetOpportunitiesRequest) (*GetOpportunitesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOpportunites not implemented")
}
func (UnimplementedUnifrontServer) mustEmbedUnimplementedUnifrontServer() {}

// UnsafeUnifrontServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UnifrontServer will
// result in compilation errors.
type UnsafeUnifrontServer interface {
	mustEmbedUnimplementedUnifrontServer()
}

func RegisterUnifrontServer(s grpc.ServiceRegistrar, srv UnifrontServer) {
	s.RegisterService(&Unifront_ServiceDesc, srv)
}

func _Unifront_TokenPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).TokenPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/tokenPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).TokenPrice(ctx, req.(*TokenPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_TokenPriceV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).TokenPriceV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/tokenPriceV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).TokenPriceV2(ctx, req.(*TokenPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_Balance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).Balance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/balance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).Balance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_ProcessingFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessingFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).ProcessingFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/processingFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).ProcessingFee(ctx, req.(*ProcessingFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_Nonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NonceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).Nonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/nonce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).Nonce(ctx, req.(*NonceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/sendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).SendTransaction(ctx, req.(*SendTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_ListTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).ListTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/listTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).ListTransaction(ctx, req.(*ListTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_UserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).UserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/userData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).UserData(ctx, req.(*UserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// func _Unifront_ExchangeTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
// 	in := new(ExchangeTokenRequest)
// 	if err := dec(in); err != nil {
// 		return nil, err
// 	}
// 	if interceptor == nil {
// 		return srv.(UnifrontServer).ExchangeTokens(ctx, in)
// 	}
// 	info := &grpc.UnaryServerInfo{
// 		Server:     srv,
// 		FullMethod: "/proto.Unifront/exchangeTokens",
// 	}
// 	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
// 		return srv.(UnifrontServer).ExchangeTokens(ctx, req.(*ExchangeTokenRequest))
// 	}
// 	return interceptor(ctx, in, info, handler)
// }

// func _Unifront_ExchangeQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
// 	in := new(ExchangeQuoteRequest)
// 	if err := dec(in); err != nil {
// 		return nil, err
// 	}
// 	if interceptor == nil {
// 		return srv.(UnifrontServer).ExchangeQuote(ctx, in)
// 	}
// 	info := &grpc.UnaryServerInfo{
// 		Server:     srv,
// 		FullMethod: "/proto.Unifront/exchangeQuote",
// 	}
// 	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
// 		return srv.(UnifrontServer).ExchangeQuote(ctx, req.(*ExchangeQuoteRequest))
// 	}
// 	return interceptor(ctx, in, info, handler)
// }

// func _Unifront_ExchangeMultiQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
// 	in := new(ExchangeMultiQuoteRequest)
// 	if err := dec(in); err != nil {
// 		return nil, err
// 	}
// 	if interceptor == nil {
// 		return srv.(UnifrontServer).ExchangeMultiQuote(ctx, in)
// 	}
// 	info := &grpc.UnaryServerInfo{
// 		Server:     srv,
// 		FullMethod: "/proto.Unifront/exchangeMultiQuote",
// 	}
// 	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
// 		return srv.(UnifrontServer).ExchangeMultiQuote(ctx, req.(*ExchangeMultiQuoteRequest))
// 	}
// 	return interceptor(ctx, in, info, handler)
// }

// func _Unifront_ExchangeSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
// 	in := new(ExchangeSwapRequest)
// 	if err := dec(in); err != nil {
// 		return nil, err
// 	}
// 	if interceptor == nil {
// 		return srv.(UnifrontServer).ExchangeSwap(ctx, in)
// 	}
// 	info := &grpc.UnaryServerInfo{
// 		Server:     srv,
// 		FullMethod: "/proto.Unifront/exchangeSwap",
// 	}
// 	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
// 		return srv.(UnifrontServer).ExchangeSwap(ctx, req.(*ExchangeSwapRequest))
// 	}
// 	return interceptor(ctx, in, info, handler)
// }

// func _Unifront_ExchangeMultiSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
// 	in := new(ExchangeMultiSwapRequest)
// 	if err := dec(in); err != nil {
// 		return nil, err
// 	}
// 	if interceptor == nil {
// 		return srv.(UnifrontServer).ExchangeMultiSwap(ctx, in)
// 	}
// 	info := &grpc.UnaryServerInfo{
// 		Server:     srv,
// 		FullMethod: "/proto.Unifront/exchangeMultiSwap",
// 	}
// 	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
// 		return srv.(UnifrontServer).ExchangeMultiSwap(ctx, req.(*ExchangeMultiSwapRequest))
// 	}
// 	return interceptor(ctx, in, info, handler)
// }

// func _Unifront_ExchangeSwapExecute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
// 	in := new(ExchangeSwapExecuteRequest)
// 	if err := dec(in); err != nil {
// 		return nil, err
// 	}
// 	if interceptor == nil {
// 		return srv.(UnifrontServer).ExchangeSwapExecute(ctx, in)
// 	}
// 	info := &grpc.UnaryServerInfo{
// 		Server:     srv,
// 		FullMethod: "/proto.Unifront/exchangeSwapExecute",
// 	}
// 	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
// 		return srv.(UnifrontServer).ExchangeSwapExecute(ctx, req.(*ExchangeSwapExecuteRequest))
// 	}
// 	return interceptor(ctx, in, info, handler)
// }

// func _Unifront_FreeTradeCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
// 	in := new(FreeTradeCountRequest)
// 	if err := dec(in); err != nil {
// 		return nil, err
// 	}
// 	if interceptor == nil {
// 		return srv.(UnifrontServer).FreeTradeCount(ctx, in)
// 	}
// 	info := &grpc.UnaryServerInfo{
// 		Server:     srv,
// 		FullMethod: "/proto.Unifront/FreeTradeCount",
// 	}
// 	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
// 		return srv.(UnifrontServer).FreeTradeCount(ctx, req.(*FreeTradeCountRequest))
// 	}
// 	return interceptor(ctx, in, info, handler)
// }

// func _Unifront_ExchangeTokenApprove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
// 	in := new(TokenApprovalRequest)
// 	if err := dec(in); err != nil {
// 		return nil, err
// 	}
// 	if interceptor == nil {
// 		return srv.(UnifrontServer).ExchangeTokenApprove(ctx, in)
// 	}
// 	info := &grpc.UnaryServerInfo{
// 		Server:     srv,
// 		FullMethod: "/proto.Unifront/ExchangeTokenApprove",
// 	}
// 	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
// 		return srv.(UnifrontServer).ExchangeTokenApprove(ctx, req.(*TokenApprovalRequest))
// 	}
// 	return interceptor(ctx, in, info, handler)
// }

// func _Unifront_ExchangeSwapSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
// 	in := new(ExchangeSignatureRequest)
// 	if err := dec(in); err != nil {
// 		return nil, err
// 	}
// 	if interceptor == nil {
// 		return srv.(UnifrontServer).ExchangeSwapSignature(ctx, in)
// 	}
// 	info := &grpc.UnaryServerInfo{
// 		Server:     srv,
// 		FullMethod: "/proto.Unifront/exchangeSwapSignature",
// 	}
// 	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
// 		return srv.(UnifrontServer).ExchangeSwapSignature(ctx, req.(*ExchangeSignatureRequest))
// 	}
// 	return interceptor(ctx, in, info, handler)
// }

func _Unifront_TxStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).TxStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/txStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).TxStatus(ctx, req.(*TxStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_GasLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GasLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).GasLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/gasLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).GasLimit(ctx, req.(*GasLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_TokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).TokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/tokenInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).TokenInfo(ctx, req.(*TokenInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_TokenDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).TokenDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/tokenDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).TokenDetail(ctx, req.(*TokenDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_BridgeChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).BridgeChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/bridgeChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).BridgeChain(ctx, req.(*BridgeChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_BridgeChainTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeChainTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).BridgeChainTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/bridgeChainTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).BridgeChainTokens(ctx, req.(*BridgeChainTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_BridgeQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).BridgeQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/bridgeQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).BridgeQuote(ctx, req.(*BridgeQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_BridgeTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).BridgeTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/bridgeTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).BridgeTransaction(ctx, req.(*BridgeTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_BridgeTransactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BridgeTransactionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).BridgeTransactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/bridgeTransactionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).BridgeTransactionStatus(ctx, req.(*BridgeTransactionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_Allowance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllowanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).Allowance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/allowance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).Allowance(ctx, req.(*AllowanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_Approve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).Approve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/approve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).Approve(ctx, req.(*ApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_GetNftCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NftCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).GetNftCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/GetNftCollections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).GetNftCollections(ctx, req.(*NftCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_GetValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CosmosValidatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).GetValidators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/GetValidators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).GetValidators(ctx, req.(*CosmosValidatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_GetCosmosAprRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CosmosAprRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).GetCosmosAprRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/GetCosmosAprRates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).GetCosmosAprRates(ctx, req.(*CosmosAprRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_GetDelegations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CosmosDelegationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).GetDelegations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/GetDelegations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).GetDelegations(ctx, req.(*CosmosDelegationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_GetCosmosCDPParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CosmosCDPParametersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).GetCosmosCDPParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/GetCosmosCDPParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).GetCosmosCDPParams(ctx, req.(*CosmosCDPParametersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_CosmosAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).CosmosAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/cosmosAssets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).CosmosAssets(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_CosmosSendTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CosmosSendTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).CosmosSendTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/cosmosSendTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).CosmosSendTx(ctx, req.(*CosmosSendTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_CosmosSimulateTX_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CosmosSimulateTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).CosmosSimulateTX(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/cosmosSimulateTX",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).CosmosSimulateTX(ctx, req.(*CosmosSimulateTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_CosmosGetBlockHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCosmosBlockHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).CosmosGetBlockHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/cosmosGetBlockHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).CosmosGetBlockHeight(ctx, req.(*GetCosmosBlockHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_GetPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionChainData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).GetPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/getPositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).GetPositions(ctx, req.(*PositionChainData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_BulkApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).BulkApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/BulkApproval",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).BulkApproval(ctx, req.(*ApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_BulkAllowance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllowanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).BulkAllowance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/BulkAllowance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).BulkAllowance(ctx, req.(*AllowanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unifront_GetOpportunites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOpportunitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnifrontServer).GetOpportunites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Unifront/GetOpportunites",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnifrontServer).GetOpportunites(ctx, req.(*GetOpportunitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Unifront_ServiceDesc is the grpc.ServiceDesc for Unifront service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Unifront_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Unifront",
	HandlerType: (*UnifrontServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "tokenPrice",
			Handler:    _Unifront_TokenPrice_Handler,
		},
		{
			MethodName: "tokenPriceV2",
			Handler:    _Unifront_TokenPriceV2_Handler,
		},
		{
			MethodName: "balance",
			Handler:    _Unifront_Balance_Handler,
		},
		{
			MethodName: "processingFee",
			Handler:    _Unifront_ProcessingFee_Handler,
		},
		{
			MethodName: "nonce",
			Handler:    _Unifront_Nonce_Handler,
		},
		{
			MethodName: "sendTransaction",
			Handler:    _Unifront_SendTransaction_Handler,
		},
		{
			MethodName: "listTransaction",
			Handler:    _Unifront_ListTransaction_Handler,
		},
		{
			MethodName: "userData",
			Handler:    _Unifront_UserData_Handler,
		},
		// {
		// 	MethodName: "exchangeTokens",
		// 	Handler:    _Unifront_ExchangeTokens_Handler,
		// },
		// {
		// 	MethodName: "exchangeQuote",
		// 	Handler:    _Unifront_ExchangeQuote_Handler,
		// },
		// {
		// 	MethodName: "exchangeMultiQuote",
		// 	Handler:    _Unifront_ExchangeMultiQuote_Handler,
		// },
		// {
		// 	MethodName: "exchangeSwap",
		// 	Handler:    _Unifront_ExchangeSwap_Handler,
		// },
		// {
		// 	MethodName: "exchangeMultiSwap",
		// 	Handler:    _Unifront_ExchangeMultiSwap_Handler,
		// },
		// {
		// 	MethodName: "exchangeSwapExecute",
		// 	Handler:    _Unifront_ExchangeSwapExecute_Handler,
		// },
		// {
		// 	MethodName: "FreeTradeCount",
		// 	Handler:    _Unifront_FreeTradeCount_Handler,
		// },
		// {
		// 	MethodName: "ExchangeTokenApprove",
		// 	Handler:    _Unifront_ExchangeTokenApprove_Handler,
		// },
		// {
		// 	MethodName: "exchangeSwapSignature",
		// 	Handler:    _Unifront_ExchangeSwapSignature_Handler,
		// },
		{
			MethodName: "txStatus",
			Handler:    _Unifront_TxStatus_Handler,
		},
		{
			MethodName: "gasLimit",
			Handler:    _Unifront_GasLimit_Handler,
		},
		{
			MethodName: "tokenInfo",
			Handler:    _Unifront_TokenInfo_Handler,
		},
		{
			MethodName: "tokenDetail",
			Handler:    _Unifront_TokenDetail_Handler,
		},
		{
			MethodName: "bridgeChain",
			Handler:    _Unifront_BridgeChain_Handler,
		},
		{
			MethodName: "bridgeChainTokens",
			Handler:    _Unifront_BridgeChainTokens_Handler,
		},
		{
			MethodName: "bridgeQuote",
			Handler:    _Unifront_BridgeQuote_Handler,
		},
		{
			MethodName: "bridgeTransaction",
			Handler:    _Unifront_BridgeTransaction_Handler,
		},
		{
			MethodName: "bridgeTransactionStatus",
			Handler:    _Unifront_BridgeTransactionStatus_Handler,
		},
		{
			MethodName: "allowance",
			Handler:    _Unifront_Allowance_Handler,
		},
		{
			MethodName: "approve",
			Handler:    _Unifront_Approve_Handler,
		},
		{
			MethodName: "GetNftCollections",
			Handler:    _Unifront_GetNftCollections_Handler,
		},
		{
			MethodName: "GetValidators",
			Handler:    _Unifront_GetValidators_Handler,
		},
		{
			MethodName: "GetCosmosAprRates",
			Handler:    _Unifront_GetCosmosAprRates_Handler,
		},
		{
			MethodName: "GetDelegations",
			Handler:    _Unifront_GetDelegations_Handler,
		},
		{
			MethodName: "GetCosmosCDPParams",
			Handler:    _Unifront_GetCosmosCDPParams_Handler,
		},
		{
			MethodName: "cosmosAssets",
			Handler:    _Unifront_CosmosAssets_Handler,
		},
		{
			MethodName: "cosmosSendTx",
			Handler:    _Unifront_CosmosSendTx_Handler,
		},
		{
			MethodName: "cosmosSimulateTX",
			Handler:    _Unifront_CosmosSimulateTX_Handler,
		},
		{
			MethodName: "cosmosGetBlockHeight",
			Handler:    _Unifront_CosmosGetBlockHeight_Handler,
		},
		{
			MethodName: "getPositions",
			Handler:    _Unifront_GetPositions_Handler,
		},
		{
			MethodName: "BulkApproval",
			Handler:    _Unifront_BulkApproval_Handler,
		},
		{
			MethodName: "BulkAllowance",
			Handler:    _Unifront_BulkAllowance_Handler,
		},
		{
			MethodName: "GetOpportunites",
			Handler:    _Unifront_GetOpportunites_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "unifront_service.proto",
}
