// Code generated by MockGen. DO NOT EDIT.
// Source: oneinch.go

// Package oneinch is a generated GoMock package.
package oneinch

import (
	reflect "reflect"
	config "bridge-allowance/config"
	pb "bridge-allowance/pkg/grpc/proto/pb"

	gomock "github.com/golang/mock/gomock"
)

// MockIOneInch is a mock of IOneInch interface.
type MockIOneInch struct {
	ctrl     *gomock.Controller
	recorder *MockIOneInchMockRecorder
}

// MockIOneInchMockRecorder is the mock recorder for MockIOneInch.
type MockIOneInchMockRecorder struct {
	mock *MockIOneInch
}

// NewMockIOneInch creates a new mock instance.
func NewMockIOneInch(ctrl *gomock.Controller) *MockIOneInch {
	mock := &MockIOneInch{ctrl: ctrl}
	mock.recorder = &MockIOneInchMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOneInch) EXPECT() *MockIOneInchMockRecorder {
	return m.recorder
}

// GetExchangeQuote mocks base method.
func (m *MockIOneInch) GetExchangeQuote(in *pb.ExchangeQuoteRequest) (*pb.ExchangeQuoteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExchangeQuote", in)
	ret0, _ := ret[0].(*pb.ExchangeQuoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExchangeQuote indicates an expected call of GetExchangeQuote.
func (mr *MockIOneInchMockRecorder) GetExchangeQuote(in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExchangeQuote", reflect.TypeOf((*MockIOneInch)(nil).GetExchangeQuote), in)
}

// GetExchangeSwap mocks base method.
func (m *MockIOneInch) GetExchangeSwap(in *pb.ExchangeSwapRequest) (*pb.ExchangeSwapResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExchangeSwap", in)
	ret0, _ := ret[0].(*pb.ExchangeSwapResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExchangeSwap indicates an expected call of GetExchangeSwap.
func (mr *MockIOneInchMockRecorder) GetExchangeSwap(in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExchangeSwap", reflect.TypeOf((*MockIOneInch)(nil).GetExchangeSwap), in)
}

// GetExchangeTokens mocks base method.
func (m *MockIOneInch) GetExchangeTokens(info config.Wallets) (*pb.ExchangeTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExchangeTokens", info)
	ret0, _ := ret[0].(*pb.ExchangeTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExchangeTokens indicates an expected call of GetExchangeTokens.
func (mr *MockIOneInchMockRecorder) GetExchangeTokens(info interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExchangeTokens", reflect.TypeOf((*MockIOneInch)(nil).GetExchangeTokens), info)
}
