package dodoEth

type Value struct {
	Symbol   string `json:"symbol"`
	Name     string `json:"name"`
	Decimals int    `json:"decimals"`
	Address  string `json:"address"`
	Source   string `json:"source"`
	OpRank   int    `json:"opRank"`
}

type ExchangeToken struct {
	Dodo     Value `json:"DODO"`
	Weth     Value `json:"WETH"`
	Eth      Value `json:"ETH"`
	Usdt     Value `json:"USDT"`
	Usdc     Value `json:"USDC"`
	WCRES    Value `json:"wCRES"`
	Wbtc     Value `json:"WBTC"`
	Link     Value `json:"LINK"`
	Snx      Value `json:"SNX"`
	Aave     Value `json:"AAVE"`
	Comp     Value `json:"COMP"`
	Yfi      Value `json:"YFI"`
	Fin      Value `json:"FIN"`
	BASv2    Value `json:"BASv2"`
	Woo      Value `json:"WOO"`
	Dai      Value `json:"DAI"`
	Rep      Value `json:"REP"`
	Zrx      Value `json:"ZRX"`
	Bat      Value `json:"BAT"`
	Stkr     Value `json:"STKR"`
	Mkr      Value `json:"MKR"`
	Susd     Value `json:"SUSD"`
	Knc      Value `json:"KNC"`
	Bnt      Value `json:"BNT"`
	Bdt      Value `json:"BDT"`
	Gno      Value `json:"GNO"`
	Ren      Value `json:"REN"`
	Omg      Value `json:"OMG"`
	Ant      Value `json:"ANT"`
	Sai      Value `json:"SAI"`
	Dth      Value `json:"DTH"`
	Foam     Value `json:"FOAM"`
	Ast      Value `json:"AST"`
	Aion     Value `json:"AION"`
	Sox      Value `json:"SOX"`
	Gen      Value `json:"GEN"`
	Storj    Value `json:"STORJ"`
	Mana     Value `json:"MANA"`
	Entrp    Value `json:"ENTRP"`
	Loom     Value `json:"LOOM"`
	Celr     Value `json:"CELR"`
	Rlc      Value `json:"RLC"`
	Icn      Value `json:"ICN"`
	Dgd      Value `json:"DGD"`
	Zil      Value `json:"ZIL"`
	CBAT     Value `json:"cBAT"`
	CDAI     Value `json:"cDAI"`
	CSAI     Value `json:"cSAI"`
	CETH     Value `json:"cETH"`
	CREP     Value `json:"cREP"`
	CUSDC    Value `json:"cUSDC"`
	CZRX     Value `json:"cZRX"`
	ZeroXBTC Value `json:"0xBTC"`
	Snt      Value `json:"SNT"`
	Spank    Value `json:"SPANK"`
	Booty    Value `json:"BOOTY"`
	Ubt      Value `json:"UBT"`
	Icx      Value `json:"ICX"`
	Nmr      Value `json:"NMR"`
	Gusd     Value `json:"GUSD"`
	Fun      Value `json:"FUN"`
	Pax      Value `json:"PAX"`
	Tusd     Value `json:"TUSD"`
	Lpt      Value `json:"LPT"`
	Enj      Value `json:"ENJ"`
	Powr     Value `json:"POWR"`
	Req      Value `json:"REQ"`
	Dnt      Value `json:"DNT"`
	Matic    Value `json:"MATIC"`
	Lrc      Value `json:"LRC"`
	Rdn      Value `json:"RDN"`
	Gst2     Value `json:"GST2"`
	Uma      Value `json:"UMA"`
	Bzrx     Value `json:"BZRX"`
	RenBTC   Value `json:"renBTC"`
	Bal      Value `json:"BAL"`
	Lend     Value `json:"LEND"`
	Ampl     Value `json:"AMPL"`
	Keep     Value `json:"KEEP"`
	MUSD     Value `json:"mUSD"`
	BUSD     Value `json:"bUSD"`
	Crv      Value `json:"CRV"`
	Sushi    Value `json:"SUSHI"`
	Swrv     Value `json:"SWRV"`
	Uni      Value `json:"UNI"`
	Inj      Value `json:"INJ"`
	Kp3R     Value `json:"KP3R"`
	Grt      Value `json:"GRT"`
	Pond     Value `json:"POND"`
	OneINCH  Value `json:"1INCH"`
	Lon      Value `json:"LON"`
	Bac      Value `json:"BAC"`
	Bas      Value `json:"BAS"`
	Defo     Value `json:"DEFO"`
	Lcx      Value `json:"LCX"`
	Pols     Value `json:"POLS"`
	Mith     Value `json:"MITH"`
	Xed      Value `json:"XED"`
	Frax     Value `json:"FRAX"`
	Fxs      Value `json:"FXS"`
	Lgcy     Value `json:"LGCY"`
	Swfl     Value `json:"SWFL"`
	Swap     Value `json:"SWAP"`
	Swg      Value `json:"SWG"`
	Octo     Value `json:"OCTO"`
	Txl      Value `json:"TXL"`
	Chi      Value `json:"CHI"`
	Prq      Value `json:"PRQ"`
	API3     Value `json:"API3"`
	Ramp     Value `json:"RAMP"`
	Zks      Value `json:"ZKS"`
	Stake    Value `json:"STAKE"`
	Rsr      Value `json:"RSR"`
	Rook     Value `json:"ROOK"`
	Bor      Value `json:"BOR"`
	Frm      Value `json:"FRM"`
	Npxs     Value `json:"NPXS"`
	Albt     Value `json:"ALBT"`
	Bao      Value `json:"BAO"`
	Wise     Value `json:"WISE"`
	Ac       Value `json:"AC"`
	Trac     Value `json:"TRAC"`
	Spi      Value `json:"SPI"`
	Bond     Value `json:"BOND"`
	Zcn      Value `json:"ZCN"`
	DG       Value `json:"$DG"`
	Mcb      Value `json:"MCB"`
	Bsg      Value `json:"BSG"`
	Bsgs     Value `json:"BSGS"`
	Arch     Value `json:"ARCH"`
	Revv     Value `json:"REVV"`
	Combo    Value `json:"COMBO"`
	Tru      Value `json:"TRU"`
	WNXM     Value `json:"wNXM"`
	Pha      Value `json:"PHA"`
	Cream    Value `json:"CREAM"`
	Open     Value `json:"OPEN"`
	Poolz    Value `json:"POOLZ"`
	Nexo     Value `json:"NEXO"`
	Mph      Value `json:"MPH"`
	Dos      Value `json:"DOS"`
	Mona     Value `json:"MONA"`
	Crbn     Value `json:"CRBN"`
	Sta      Value `json:"STA"`
	Ptf      Value `json:"PTF"`
	Nord     Value `json:"NORD"`
	Yop      Value `json:"YOP"`
	Cudos    Value `json:"CUDOS"`
	Gro      Value `json:"GRO"`
	Value    Value `json:"VALUE"`
	Mm       Value `json:"MM"`
	Zap      Value `json:"ZAP"`
	Kit      Value `json:"KIT"`
	Roya     Value `json:"ROYA"`
	Wsta     Value `json:"WSTA"`
	Snow     Value `json:"SNOW"`
	Badger   Value `json:"BADGER"`
	Hegic    Value `json:"HEGIC"`
	Mta      Value `json:"MTA"`
	Pros     Value `json:"PROS"`
	Digg     Value `json:"DIGG"`
	Rune     Value `json:"RUNE"`
	Alpha    Value `json:"ALPHA"`
	Dia      Value `json:"DIA"`
	Rari     Value `json:"RARI"`
	Rndr     Value `json:"RNDR"`
	Nftx     Value `json:"NFTX"`
	Kex      Value `json:"KEX"`
	Bot      Value `json:"BOT"`
	Mir      Value `json:"MIR"`
	RenDOGE  Value `json:"renDOGE"`
	Donut    Value `json:"DONUT"`
	Fwt      Value `json:"FWT"`
	Gme      Value `json:"GME"`
	Dis      Value `json:"DIS"`
	Pnt      Value `json:"PNT"`
	Nct      Value `json:"NCT"`
	Ndx      Value `json:"NDX"`
	Layer    Value `json:"LAYER"`
	Ddx      Value `json:"DDX"`
	Easy     Value `json:"EASY"`
	Armor    Value `json:"ARMOR"`
	Trade    Value `json:"TRADE"`
	Bondly   Value `json:"BONDLY"`
	Mrph     Value `json:"MRPH"`
	Uncx     Value `json:"UNCX"`
	Cap      Value `json:"CAP"`
	Lit      Value `json:"LIT"`
	Skl      Value `json:"SKL"`
	Nu       Value `json:"NU"`
	Amp      Value `json:"AMP"`
	Room     Value `json:"ROOM"`
	Paid     Value `json:"PAID"`
	Unistake Value `json:"UNISTAKE"`
	Dec      Value `json:"DEC"`
	Perp     Value `json:"PERP"`
	Apy      Value `json:"APY"`
	Qrx      Value `json:"QRX"`
	Xft      Value `json:"XFT"`
	Buidl    Value `json:"buidl"`
	Emb      Value `json:"EMB"`
	Cws      Value `json:"CWS"`
	Fnt      Value `json:"FNT"`
	Mark     Value `json:"MARK"`
	Torn     Value `json:"TORN"`
	RenBCH   Value `json:"renBCH"`
	RenZEC   Value `json:"renZEC"`
	Om       Value `json:"OM"`
	Front    Value `json:"FRONT"`
	Fyz      Value `json:"FYZ"`
	Wszo     Value `json:"WSZO"`
	Super    Value `json:"SUPER"`
	Far      Value `json:"FAR"`
	Mod      Value `json:"MOD"`
	Mask     Value `json:"MASK"`
	Muse     Value `json:"MUSE"`
	Hopr     Value `json:"HOPR"`
	Math     Value `json:"MATH"`
	Bel      Value `json:"BEL"`
	VETH     Value `json:"vETH"`
	Rad      Value `json:"RAD"`
	Matter   Value `json:"MATTER"`
	Ghst     Value `json:"GHST"`
	Ocean    Value `json:"OCEAN"`
	Etha     Value `json:"ETHA"`
	Reef     Value `json:"REEF"`
	CFi      Value `json:"CFi"`
	Tops     Value `json:"TOPS"`
	Paint    Value `json:"PAINT"`
	Skey     Value `json:"Skey"`
	Ovr      Value `json:"OVR"`
	Bdp      Value `json:"BDP"`
	Dego     Value `json:"DEGO"`
	LYXe     Value `json:"LYXe"`
	Bank     Value `json:"BANK"`
	B20      Value `json:"B20"`
	Chz      Value `json:"CHZ"`
	Chr      Value `json:"CHR"`
	Kine     Value `json:"KINE"`
	Rly      Value `json:"RLY"`
	Mft      Value `json:"MFT"`
	Rgt      Value `json:"RGT"`
	Akro     Value `json:"AKRO"`
	Bepro    Value `json:"BEPRO"`
	Alice    Value `json:"ALICE"`
	Bird     Value `json:"BIRD"`
	Stmx     Value `json:"STMX"`
	Ust      Value `json:"UST"`
	Insur    Value `json:"INSUR"`
	Lina     Value `json:"LINA"`
	Umx      Value `json:"UMX"`
	Ern      Value `json:"ERN"`
	Amlt     Value `json:"AMLT"`
	Dent     Value `json:"DENT"`
	Sfi      Value `json:"SFI"`
	Nfy      Value `json:"NFY"`
	Tidal    Value `json:"TIDAL"`
	Audio    Value `json:"AUDIO"`
	Alcx     Value `json:"ALCX"`
	Vera     Value `json:"VERA"`
	Pickle   Value `json:"PICKLE"`
	Vsp      Value `json:"VSP"`
	Labs     Value `json:"LABS"`
	Gfx      Value `json:"GFX"`
	Fnx      Value `json:"FNX"`
	Rbc      Value `json:"RBC"`
	K21      Value `json:"K21"`
	Mtl      Value `json:"MTL"`
	Stn      Value `json:"STN"`
	Ogn      Value `json:"OGN"`
	Cro      Value `json:"CRO"`
	Pmon     Value `json:"PMON"`
	Shopx    Value `json:"SHOPX"`
	Blank    Value `json:"BLANK"`
	Fei      Value `json:"FEI"`
	Tribe    Value `json:"TRIBE"`
	Rai      Value `json:"Rai"`
	Aioz     Value `json:"AIOZ"`
	Pundix   Value `json:"PUNDIX"`
	Get      Value `json:"GET"`
	Meta     Value `json:"Meta"`
	Ktn      Value `json:"KTN"`
	Atri     Value `json:"ATRI"`
	Shib     Value `json:"SHIB"`
	Val      Value `json:"VAL"`
	Kono     Value `json:"KONO"`
	Xyo      Value `json:"XYO"`
	Forth    Value `json:"FORTH"`
	Cc       Value `json:"CC"`
	Tel      Value `json:"TEL"`
	Cards    Value `json:"CARDS"`
	Hbt      Value `json:"HBT"`
	Hoo      Value `json:"HOO"`
	Mpl      Value `json:"MPL"`
	Trb      Value `json:"TRB"`
	Kai      Value `json:"KAI"`
	Akita    Value `json:"AKITA"`
	Kishu    Value `json:"KISHU"`
	Hokk     Value `json:"HOKK"`
	Husky    Value `json:"HUSKY"`
	Woofy    Value `json:"WOOFY"`
	Elon     Value `json:"ELON"`
	O3       Value `json:"O3"`
	Gdt      Value `json:"GDT"`
	Ctsi     Value `json:"CTSI"`
	Beone    Value `json:"BEONE"`
}
